# Generated by Django 4.2.11 on 2025-02-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunmodelleri', '0004_sepet_is_complated'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='urunler/'),
        ),
    ]
