# Generated by Django 4.2.11 on 2025-02-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunmodelleri', '0005_urunler_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepeturunleri',
            name='beden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urunmodelleri.beden'),
        ),
        migrations.AddField(
            model_name='sepeturunleri',
            name='renk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urunmodelleri.renk'),
        ),
    ]
