# Generated by Django 4.2.11 on 2025-02-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magza', '0010_alter_mpuan_unique_together'),
        ('urunmodelleri', '0006_sepeturunleri_beden_sepeturunleri_renk'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='magza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magza.magzalar'),
        ),
    ]
