# Generated by Django 4.2.11 on 2025-02-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunmodelleri', '0006_sepeturunleri_beden_sepeturunleri_renk'),
        ('users', '0003_rename_ad_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriurun',
            name='beden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='urunmodelleri.beden'),
        ),
        migrations.AddField(
            model_name='favoriurun',
            name='renk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='urunmodelleri.renk'),
        ),
    ]
